eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
microservice:
  payment-service:
    endpoints:
      endpoint:
        urli: http://PAYMENT-SERVICE/payment/doPayment 
  order-service:
    endpoints:
      endpoint:
        urli: http://ORDER-SERVICE/order/bookOrder
